import AppKit
import Carbon.HIToolbox
import Testing

@testable import MyDikte

/// Everything about the insertion path that can be proven without typing into the user's screen.
///
/// Nothing here posts an event. A synthetic Cmd-V lands in whatever window has focus, which during
/// a test run is the real desktop, so the four events are constructed and inspected instead, and
/// the clipboard write is exercised against a private named pasteboard so the general clipboard is
/// never touched. Whether the paste actually lands at the caret of TextEdit, Terminal, Chrome and
/// VS Code is verified by hand through the entry in `App/DebugMenu+Output.swift`.
@Suite("TextInserter")
@MainActor
struct TextInserterTests {
    private static let turkishSample = "Kubernetes'e deploy ettim, ölçüm 1.09 s."

    @Test("the paste keystroke is the physical V, key code 9, not the character")
    func pasteKeyCodeIsPhysicalV() {
        // A "Turkish - QWERTY ⌘" style layout remaps while Command is held, so a character-based
        // keystroke resolves to the wrong key. Locking the number down here stops a later reader
        // from "simplifying" it back to a character.
        #expect(TextInserter.pasteKeyCode == 9)
        #expect(TextInserter.pasteKeyCode == CGKeyCode(kVK_ANSI_V))
        #expect(TextInserter.commandKeyCode == CGKeyCode(kVK_Command))
    }

    @Test("the sequence is Command down, V down, V up, Command up, with Command held across the V")
    func pasteSequenceHasTheRightShape() throws {
        let source = try #require(
            CGEventSource(stateID: .combinedSessionState),
            "Apple's documented state for a program posting inside a login session"
        )
        let sequence = try TextInserter.makePasteSequence(source: source)

        // Measured on macOS 26: a synthetic Command key event comes back as `.flagsChanged` for
        // both directions, never as a key down or up, so its flags are what carry press and release.
        #expect(sequence.commandDown.type == .flagsChanged)
        #expect(sequence.commandUp.type == .flagsChanged)
        #expect(sequence.vDown.type == .keyDown)
        #expect(sequence.vUp.type == .keyUp)

        let commandCode = Int64(TextInserter.commandKeyCode)
        let pasteCode = Int64(TextInserter.pasteKeyCode)
        #expect(sequence.commandDown.getIntegerValueField(.keyboardEventKeycode) == commandCode)
        #expect(sequence.vDown.getIntegerValueField(.keyboardEventKeycode) == pasteCode)
        #expect(sequence.vUp.getIntegerValueField(.keyboardEventKeycode) == pasteCode)
        #expect(sequence.commandUp.getIntegerValueField(.keyboardEventKeycode) == commandCode)

        // The V events carry the Command flag as well as being surrounded by physical Command
        // events: a virtualisation host honours only the real modifier events, an ordinary app
        // reads the flag. They inherit Command-down's flags exactly, device-dependent bits and all,
        // which is what real hardware sends.
        #expect(sequence.commandDown.flags.contains(.maskCommand))
        #expect(!sequence.commandUp.flags.contains(.maskCommand))
        #expect(sequence.vDown.flags == sequence.commandDown.flags)
        #expect(sequence.vUp.flags == sequence.commandDown.flags)
    }

    @Test("the transcript is written with the three clipboard-manager markers")
    func writeMarksTheItemForClipboardManagers() throws {
        #expect(
            TextInserter.markerTypes.map(\.rawValue) == [
                "org.nspasteboard.TransientType",
                "org.nspasteboard.ConcealedType",
                "org.nspasteboard.AutoGeneratedType",
            ]
        )

        // A private named pasteboard, as in `evidence/step-11-pasteboard-probe.txt`, so this test
        // never touches what the user has on the general clipboard.
        let pasteboard = NSPasteboard(name: NSPasteboard.Name("com.anilcan.mydikte.tests"))
        try TextInserter.write(Self.turkishSample, to: pasteboard)

        let types = pasteboard.types ?? []
        for marker in TextInserter.markerTypes {
            #expect(types.contains(marker))
        }
        #expect(types.contains(.string))
        #expect(pasteboard.string(forType: .string) == Self.turkishSample)

        pasteboard.releaseGlobally()
    }

    @Test("the secure-input failure names the password field as the cause")
    func secureInputFailureNamesTheCause() throws {
        let message = try #require(TextInserter.InsertionError.secureInputActive.errorDescription)
        #expect(message.localizedCaseInsensitiveContains("password"))
    }

    @Test("every failure after the clipboard write points the user at the clipboard")
    func failuresPointAtTheClipboard() throws {
        // The contract the pipeline depends on: a dictation is never lost, so a failure has to say
        // where the text ended up.
        let failures: [TextInserter.InsertionError] = [
            .secureInputActive,
            .targetUnavailable(applicationName: "TextEdit"),
            .activationTimedOut(applicationName: "TextEdit"),
            .eventSourceUnavailable,
            .eventCreationFailed,
        ]

        for failure in failures {
            let message = try #require(failure.errorDescription)
            #expect(message.localizedCaseInsensitiveContains("clipboard"), "\(failure)")
        }
    }

    @Test("a failure that names an application quotes the one the user was in")
    func failureNamesTheTargetApplication() throws {
        let message = try #require(
            TextInserter.InsertionError.activationTimedOut(applicationName: "TextEdit").errorDescription
        )
        #expect(message.contains("TextEdit"))
    }
}

/// The value that carries "the app the user was in when they started talking" from the capture site
/// to the insertion site.
@Suite("FocusTarget")
struct FocusTargetTests {
    @Test("the display name prefers the localized name")
    func displayNamePrefersLocalizedName() {
        let target = FocusTarget(
            processIdentifier: 501,
            bundleIdentifier: "com.apple.TextEdit",
            localizedName: "TextEdit"
        )
        #expect(target.displayName == "TextEdit")
    }

    @Test("the display name falls back to the bundle identifier, then to the process identifier")
    func displayNameFallsBack() {
        let withoutName = FocusTarget(
            processIdentifier: 501,
            bundleIdentifier: "com.apple.TextEdit",
            localizedName: nil
        )
        #expect(withoutName.displayName == "com.apple.TextEdit")

        let anonymous = FocusTarget(processIdentifier: 501, bundleIdentifier: nil, localizedName: nil)
        #expect(anonymous.displayName.contains("501"))
    }
}
