import AppKit
import Carbon.HIToolbox

/// Puts a finished dictation at the caret of the application the user was in, by writing the text to
/// the clipboard and posting a synthetic Cmd-V.
///
/// The clipboard route is what all four reference implementations do, and none of them writes text
/// through the Accessibility API: an `AXUIElementSetAttributeValue` on the selected-text attribute is
/// unimplemented in most editors (terminals, Electron shells, anything drawing its own text view) and
/// fails there without an error, which is worse than not trying.
///
/// The clipboard is deliberately never restored, and never read. A restore is a race against the
/// target application's own paste, and a programmatic read is what can raise the macOS 15.4
/// `NSPasteboard.AccessBehavior` prompt. Leaving the transcript on the clipboard is also the safety
/// net under every failure below: whatever goes wrong, the dictation is one manual Cmd-V away.
@MainActor
enum TextInserter {
    /// Physical V. Not the character: on a layout that remaps to QWERTY while Command is held, a
    /// character-based keystroke resolves to the wrong key. Key code 9 bypasses layout translation,
    /// and `kVK_ANSI_V == 9` is verified in `evidence/step-11-pasteboard-probe.txt`.
    static let pasteKeyCode = CGKeyCode(kVK_ANSI_V)

    /// The physical Command key. Posted as real key events as well as set as a flag on the V events:
    /// Pindrop's own comment at `OutputManager.swift:215-216` records that a virtualisation host
    /// ignores `.maskCommand` on its own and honours only genuine modifier key events.
    static let commandKeyCode = CGKeyCode(kVK_Command)

    /// Community-convention pasteboard types that ask clipboard managers to skip this item, so a
    /// dictation (which may be anything the user just said) does not land in a clipboard history.
    /// These are plain custom UTI strings rather than an Apple API: there is no
    /// `NSPasteboard.ContentType.concealed` to reach for.
    static let markerTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    /// How long the target application gets to actually come forward before the paste is abandoned.
    /// Abandoning is the safe outcome: a keystroke posted while the wrong window has focus types the
    /// dictation into it.
    private static let activationTimeout: Duration = .milliseconds(500)

    private static let activationPollInterval: Duration = .milliseconds(10)

    /// Gap between the four posted events. Both references interleave one here (VoiceInk 10 ms,
    /// Pindrop 50 ms) rather than posting the sequence back to back; 30 ms in total is invisible
    /// against this app's 1.5 s budget, so this follows two shipping implementations instead of
    /// betting against them.
    private static let keyEventInterval: Duration = .milliseconds(10)

    /// Why an insertion did not reach the caret. Every case after the clipboard write says the text
    /// is still on the clipboard, because the pipeline's rule is that a dictation is never lost.
    enum InsertionError: Error, LocalizedError, Equatable {
        case clipboardWriteFailed
        case secureInputActive
        case targetUnavailable(applicationName: String)
        case activationTimedOut(applicationName: String)
        case eventSourceUnavailable
        case eventCreationFailed

        var errorDescription: String? {
            switch self {
            case .clipboardWriteFailed:
                "macOS refused the clipboard write, so the text was neither pasted nor copied."
            case .secureInputActive:
                """
                A password field has keyboard input locked (secure input), so the paste keystroke \
                was not sent. The text is on the clipboard: paste it once the password field loses \
                focus.
                """
            case .targetUnavailable(let applicationName):
                """
                \(applicationName) would not come forward, most likely because it has quit, so \
                nothing was pasted. The text is on the clipboard.
                """
            case .activationTimedOut(let applicationName):
                """
                \(applicationName) did not come to the front in time, so the paste was abandoned \
                rather than typed into another app. The text is on the clipboard.
                """
            case .eventSourceUnavailable:
                "macOS refused to create a keyboard event source, so nothing was pasted. The text is on the clipboard."
            case .eventCreationFailed:
                "macOS refused to create the paste keystroke, so nothing was pasted. The text is on the clipboard."
            }
        }
    }

    /// The four events of a Cmd-V, constructed but not yet posted, so the shape of the sequence can
    /// be asserted without typing into whatever window has focus.
    struct PasteSequence {
        let commandDown: CGEvent
        let vDown: CGEvent
        let vUp: CGEvent
        let commandUp: CGEvent
    }

    /// Writes `text` to the clipboard and pastes it into `target`.
    ///
    /// - Parameters:
    ///   - text: the finished dictation.
    ///   - target: the application captured when recording started.
    /// - Throws: `InsertionError` naming what went wrong, or `CancellationError` when the caller
    ///   cancels mid-sequence, in which case Command is released before it propagates.
    static func insert(_ text: String, into target: FocusTarget) async throws {
        // 1. The clipboard write comes first so that every failure below still leaves the dictation
        //    somewhere the user can reach. This is the one ordering that keeps "a dictation is never
        //    lost" true even when the keystroke never happens.
        try write(text, to: .general)

        // 2. Secure input, which a focused password field turns on, withholds keyboard events from
        //    synthetic posting and reports nothing at all. Posting into it would claim a success
        //    that never happened, so it is a named failure instead.
        if IsSecureEventInputEnabled() {
            throw InsertionError.secureInputActive
        }

        // 3. The user may have moved to another window while the transcription was in flight.
        try await bringForward(target)

        // 4. Only now, with the intended window in front, does the keystroke go out.
        try await postPasteKeystroke()
    }

    /// Writes `text` to `pasteboard`, marked so clipboard managers skip it.
    ///
    /// Deliberately never reads the pasteboard back, not even to verify the write: a programmatic
    /// read is what raises the `NSPasteboard.AccessBehavior` prompt on macOS 15.4 and later, and
    /// `setString`'s own result already answers the only question worth asking.
    static func write(_ text: String, to pasteboard: NSPasteboard) throws {
        pasteboard.declareTypes([.string] + markerTypes, owner: nil)

        guard pasteboard.setString(text, forType: .string) else {
            throw InsertionError.clipboardWriteFailed
        }

        // The markers carry no payload; their presence is the whole signal. A marker that fails to
        // write only means a clipboard manager may keep this item in its history, which is not
        // worth failing an insertion the user is waiting for, so the result is handled by being
        // deliberately ignored here rather than thrown.
        for marker in markerTypes {
            _ = pasteboard.setData(Data(), forType: marker)
        }
    }

    /// Builds the Cmd-V sequence from `source`, without posting anything.
    static func makePasteSequence(source: CGEventSource) throws -> PasteSequence {
        guard
            let commandDown = CGEvent(keyboardEventSource: source, virtualKey: commandKeyCode, keyDown: true),
            let vDown = CGEvent(keyboardEventSource: source, virtualKey: pasteKeyCode, keyDown: true),
            let vUp = CGEvent(keyboardEventSource: source, virtualKey: pasteKeyCode, keyDown: false),
            let commandUp = CGEvent(keyboardEventSource: source, virtualKey: commandKeyCode, keyDown: false)
        else {
            throw InsertionError.eventCreationFailed
        }

        // A synthetic Command key event is not a `.keyDown`: macOS delivers it as `.flagsChanged`
        // for both `keyDown: true` and `keyDown: false` (measured on macOS 26, raw type 12), so its
        // flags are the only thing separating the press from the release. macOS builds those flags
        // correctly already, Command-down carrying `.maskCommand` plus the device-dependent
        // left-Command bit and Command-up carrying neither, so the union below only guarantees the
        // modifier flag rather than replacing what the system set.
        //
        // The V events then inherit exactly that modifier state, which keeps the device-dependent
        // bit a real keypress carries. Both references assign a bare `.maskCommand` here, which
        // drops it.
        let heldModifiers = commandDown.flags.union(.maskCommand)
        commandDown.flags = heldModifiers
        vDown.flags = heldModifiers
        vUp.flags = heldModifiers

        return PasteSequence(commandDown: commandDown, vDown: vDown, vUp: vUp, commandUp: commandUp)
    }

    /// Brings `target` forward and waits until the window server agrees it is frontmost.
    ///
    /// AppKit documents that activation is asynchronous and not even guaranteed to happen, so a
    /// keystroke posted straight after `activate()` can be delivered to the window the user has
    /// since moved to. Polling until the target really is frontmost is what makes "the keystroke
    /// lands in the intended window" a checked condition rather than a hope, and it costs nothing in
    /// the common case where the target never lost focus.
    private static func bringForward(_ target: FocusTarget) async throws {
        guard target.activate() else {
            throw InsertionError.targetUnavailable(applicationName: target.displayName)
        }

        let deadline = ContinuousClock.now + activationTimeout
        while !target.isFrontmost {
            if ContinuousClock.now >= deadline {
                throw InsertionError.activationTimedOut(applicationName: target.displayName)
            }
            try await Task.sleep(for: activationPollInterval)
        }
    }

    /// Posts Command-down, V-down, V-up, Command-up to the HID event tap.
    private static func postPasteKeystroke() async throws {
        // `.combinedSessionState` is Apple's documented recommendation for a program posting events
        // from inside a login session. The references disagree here and both are off-guidance:
        // `.privateState` posts into a state only the creating process sees, `.hidSystemState`
        // claims to be the hardware.
        guard let source = CGEventSource(stateID: .combinedSessionState) else {
            throw InsertionError.eventSourceUnavailable
        }

        // Everything is constructed before anything is posted, so a construction failure cannot
        // leave a modifier held.
        let sequence = try makePasteSequence(source: source)

        var commandIsDown = false
        defer {
            if commandIsDown {
                // A Command left down makes the user's keyboard unusable, so it is released even
                // when the sequence was abandoned midway; a cancellation between the two Command
                // events is the realistic way in.
                sequence.commandUp.post(tap: .cghidEventTap)
            }
        }

        sequence.commandDown.post(tap: .cghidEventTap)
        commandIsDown = true
        try await Task.sleep(for: keyEventInterval)

        sequence.vDown.post(tap: .cghidEventTap)
        try await Task.sleep(for: keyEventInterval)

        sequence.vUp.post(tap: .cghidEventTap)
        try await Task.sleep(for: keyEventInterval)

        sequence.commandUp.post(tap: .cghidEventTap)
        commandIsDown = false
    }
}
